### ISSUE TITLE
Package contains file(s) named "jquery.js" causing "Multiple matches found for jquery.js" exception

### ISSUE THREAD

**Issue by hkasabas** [webjars/ckeditor#10]
Hi,

  CKEditor package contains multiple (3) files named "jquery.js" (eg. /META-INF/resources/webjars/ckeditor/4.5.4/basic/adapters/jquery.js) which cause webjars loader to throw following exception:

Caused by: org.webjars.MultipleMatchesException: Multiple matches found for jquery.js. Please provide a more specific path, for example by including a version number.

Those file don't even contain jQuery itself but editor's adapter for jQuery, but it's naming is obviously causing this issue.

Tnx!

**Comment by jamesward** [comment]
Instead of changing this WebJar you can use a more specific way to locate the asset:
https://github.com/webjars/webjars-locator-core#obtain-the-full-path-of-an-asset

For instance, use the `locator.getFullPathExact` method.
