### ISSUE TITLE
Please deploy 4.7.1

### ISSUE THREAD

**Issue by 2point718** [webjars/ckeditor#16]
Could you please deploy 4.7.1 to [maven central repo](https://mvnrepository.com/artifact/org.webjars/ckeditor) now that [4.7.1](http://ckeditor.com/blog/CKEditor-4.7.1-released) is released (http://ckeditor.com/blog/CKEditor-4.7.1-released) ?

**Comment by jamesward** [comment]
This will be released shortly.
