### ISSUE TITLE
Different versions for basic, standard & full packages

### ISSUE THREAD

**Issue by adrianhurt** [webjars/ckeditor#5]
Hi,

There are 3 different packages for CKEditor you can download: Basic, Standard & Full. Maybe it would be useful to have different webjars or different versions within this webjar for them.

Thanks!

**Comment by jamesward** [comment]
Right now the WebJar is the Full one.  What about putting all 3 in this WebJar but under subdirs: `basic`, `standard`, `full`?

**Comment by adrianhurt** [comment]
It's another option… Although it would require to download code you will never use.

**Comment by jamesward** [comment]
Since just the developer will have to do that once I'd rather go that route since all three of these will always be released at the same time.

**Comment by adrianhurt** [comment]
ok, thanks!
